### PR TITLE
refcounting

### LINKED ISSUE #46: Bring up dependent interfaces on ifup
With

```
auto enp1s0
iface enp1s0
        address 192.168.20.123/24
        gateway 192.168.20.1
        vrf vrf_external

auto vrf_external
iface vrf_external
        vrf-table 1023

```

bringing up enp1s0 results in an error:

```

# ifup enp1s0
Error: argument "vrf_external" is wrong: Device does not exist

ifup: failed to change interface enp1s0 state to 'up'
```

I think ifupdown-ng should bring up dependent interfaces as well on ifup. If not by default, we need somethink like `--with-depends` / `-w`.

### LINKED ISSUE #57: interface refcounting
Right now, we do not perform refcounting on interfaces at all.

This means a dependency-based ifdown can take out the entire network.

We should resolve that for 0.9.

### LINKED ISSUE #63: dependent interfaces might be configured twice
With the following config

```
iface enp1s0
        address xxx
        gateway yyyy
        vrf vrf_external

auto vrf_external
iface vrf_external
        vrf-table 1023
```

interface `vrf_external` will be configured twice on `ifup -a` which raises an error. The first run is done because of the dependency the second one regularly. It seems when configuring an interface based on a dependency it should be marked as configured.

### PR DESCRIPTION
**Pull request by kaniini**
This adds refcounting to the dependency tree walker by changing `lif_state` functions to operate on `lif_state_record` objects.

Refcounting is used to track which interfaces can be safely torn down without having to compute all possible views of the dependency graph and cross-checking them.

Closes #57.
Closes #63.
Closes #46.

### CODE REVIEW

File: libifupdown/state.c [hunk 1]
```diff
@@ -16,24 +16,32 @@
...
 	{
-		char *ifname = linebuf;
+		char *bufp = linebuf;
+		char *ifname = lif_next_token(&bufp);
+		char *refcount = lif_next_token(&bufp);
+		size_t rc = 1;
 		char *equals_p = strchr(linebuf, '=');
 
+		if (*refcount)
+			rc = strtoul(refcount, NULL, 10);
```
Comment (BarbarossaTM) [inline libifupdown/state.c:35]: Do we trust the implementation of `strtoul()` to return 0 on invalid input? According to the man page I consulted that's left to the implementation (MAY).

Comment (kaniini) [reply libifupdown/state.c:36]: i added a commit just now checking for ULONG_MAX or 0.  should be sufficient.  POSIX requires ULONG_MAX anyway.
